### ISSUE TITLE
Unable to install packages on Xenial/Bionic

### ISSUE THREAD

**Issue by jsimpso** [canonical/operator-libs-linux#60]
To reproduce:

Prepare up a LXD container
```bash
lxc launch ubuntu:xenial xenial
lxc exec xenial bash
wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
python3
```
Try to install a package
```python
import apt
apt.add_package(["python3-pymongo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/apt.py", line 761, in add_package
    pkg, success = _add(p, version, arch)
  File "/root/apt.py", line 802, in _add
    pkg.ensure(state=PackageState.Present)
  File "/root/apt.py", line 290, in ensure
    self._add()
  File "/root/apt.py", line 265, in _add
    optargs=["--option=Dpkg::Options::=--force-confold"],
  File "/root/apt.py", line 258, in _apt
    ) from None
apt.PackageError: Could not install package(s) [['python3-pymongo=3.2-1build1']]: None
```
Without `env` specified installation succeeds:
```bash
sed -i s'/check_call(_cmd, env=env, stderr=PIPE, stdout=PIPE)/check_call(_cmd, stderr=PIPE, stdout=PIPE)/' apt.py
```
```python
python3
Python 3.5.2 (default, Jan 26 2021, 13:30:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> apt.add_package(["python3-pymongo"])
<apt.DebianPackage: {'_arch': 'amd64', '_name': 'python3-pymong', '_version': <apt.Version: {'_epoch': '', '_version': '3.2-1build1'}>, '_state': <PackageState.Present: 'present'>}>
```

The root cause of this seems to be `PATH` not making its way to the subprocess env, per `dpkg: error: PATH is not set` in the following output:

```python
root@xenial:~# python3
Python 3.5.2 (default, Jan 26 2021, 13:30:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> _cmd = ['apt-get', '-y', '--option=Dpkg::Options::=--force-confold', 'install', 'python3-pymongo=3.2-1build1']
>>> env={"DEBIAN_FRONTEND": "noninteractive"}
>>> subprocess.run(_cmd, env=env)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  python3-pymongo-ext
Suggested packages:
  python-pymongo-doc
The following NEW packages will be installed:
  python3-pymongo python3-pymongo-ext
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/109 kB of archives.
After this operation, 674 kB of additional disk space will be used.
debconf: delaying package configuration, since apt-utils is not installed
dpkg: error: PATH is not set
E: Sub-process /usr/bin/dpkg returned an error code (2)
CompletedProcess(args=['apt-get', '-y', '--option=Dpkg::Options::=--force-confold', 'install', 'python3-pymongo=3.2-1build1'], returncode=100)
>>> 
```

As the default behaviour when `env` is not specified is to [inherit from the parent shell](https://docs.python.org/3.5/library/subprocess.html#popen-constructor), I propose a change to copy the current `os.environ` before we specify any new keys.
> If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.

**Comment by benhoyt** [comment]
This was fixed in #61
